# -*- encoding: utf-8 -*-

def say(uni):
    return uni + generate(classify(featurize(uni)))

def generate(label):
    return label

def featurize(inp):
    return { "unigram": inp[-1:], "bigram": inp[-2:] }

def classify(featureset) :
    if "bigram" in featureset:
      if featureset["bigram"] == u'ag': return u'nak'
      elif featureset["bigram"] == u'aj': return u'nak'
      elif featureset["bigram"] == u'al': return u'nak'
      elif featureset["bigram"] == u'an': return u'nak'
      elif featureset["bigram"] == u'ap': return u'nak'
      elif featureset["bigram"] == u'ar': return u'nak'
      elif featureset["bigram"] == u'at': return u'nak'
      elif featureset["bigram"] == u'ba': return u'nak'
      elif featureset["bigram"] == u'cs': return u'nak'
      elif featureset["bigram"] == u'd\u0151': return u'nek'
      elif featureset["bigram"] == u'eg': return u'nek'
      elif featureset["bigram"] == u'el': return u'nek'
      elif featureset["bigram"] == u'em': return u'nek'
      elif featureset["bigram"] == u'er': return u'nek'
      elif featureset["bigram"] == u'et': return u'nek'
      elif featureset["bigram"] == u'ez': return u'nek'
      elif featureset["bigram"] == u'ga': return u'nak'
      elif featureset["bigram"] == u'gy': return u'nak'
      elif featureset["bigram"] == u'ha': return u'nak'
      elif featureset["bigram"] == u'ia': return u'nak'
      elif featureset["bigram"] == u'je': return u'nek'
      elif featureset["bigram"] == u'jj': return u'nak'
      elif featureset["bigram"] == u'ka': return u'nak'
      elif featureset["bigram"] == u'kk': return u'nek'
      elif featureset["bigram"] == u'k\xf3': return u'nak'
      elif featureset["bigram"] == u'li': return u'nak'
      elif featureset["bigram"] == u'll': return u'nak'
      elif featureset["bigram"] == u'lp': return u'nak'
      elif featureset["bigram"] == u'lt': return u'nak'
      elif featureset["bigram"] == u'lv': return u'nek'
      elif featureset["bigram"] == u'ly': return u'nek'
      elif featureset["bigram"] == u'l\xf3': return u'nak'
      elif featureset["bigram"] == u'l\u0151': return u'nek'
      elif featureset["bigram"] == u'nd': return u'nek'
      elif featureset["bigram"] == u'ng': return u'nak'
      elif featureset["bigram"] == u'ny': return u'nek'
      elif featureset["bigram"] == u'n\xf3': return u'nak'
      elif featureset["bigram"] == u'n\xfa': return u'nak'
      elif featureset["bigram"] == u'og': return u'nak'
      elif featureset["bigram"] == u'ok': return u'nak'
      elif featureset["bigram"] == u'om': return u'nak'
      elif featureset["bigram"] == u'on': return u'nak'
      elif featureset["bigram"] == u'or': return u'nak'
      elif featureset["bigram"] == u'os': return u'nak'
      elif featureset["bigram"] == u'ot': return u'nak'
      elif featureset["bigram"] == u'pu': return u'nak'
      elif featureset["bigram"] == u'p\xf3': return u'nak'
      elif featureset["bigram"] == u'p\u0151': return u'nek'
      elif featureset["bigram"] == u'ra': return u'nak'
      elif featureset["bigram"] == u'rc': return u'nak'
      elif featureset["bigram"] == u'rs': return u'nak'
      elif featureset["bigram"] == u'rt': return u'nak'
      elif featureset["bigram"] == u'r\xfa': return u'nak'
      elif featureset["bigram"] == u'r\u0151': return u'nek'
      elif featureset["bigram"] == u'st': return u'nek'
      elif featureset["bigram"] == u'sz': return u'nek'
      elif featureset["bigram"] == u's\u0151': return u'nek'
      elif featureset["bigram"] == u'te': return u'nek'
      elif featureset["bigram"] == u't\u0151': return u'nek'
      elif featureset["bigram"] == u'um': return u'nak'
      elif featureset["bigram"] == u'us': return u'nak'
      elif featureset["bigram"] == u'ya': return u'nak'
      elif featureset["bigram"] == u'yv': return u'nek'
      elif featureset["bigram"] == u'za': return u'nak'
      elif featureset["bigram"] == u'z\xf3': return u'nak'
      elif featureset["bigram"] == u'z\u0151': return u'nek'
      elif featureset["bigram"] == u'\xe1g': return u'nak'
      elif featureset["bigram"] == u'\xe1j': return u'nak'
      elif featureset["bigram"] == u'\xe1m': return u'nak'
      elif featureset["bigram"] == u'\xe1r': return u'nak'
      elif featureset["bigram"] == u'\xe1s': return u'nak'
      elif featureset["bigram"] == u'\xe1z': return u'nak'
      elif featureset["bigram"] == u'\xe9d': return u'nak'
      elif featureset["bigram"] == u'\xe9g': return u'nek'
      elif featureset["bigram"] == u'\xe9k': return u'nek'
      elif featureset["bigram"] == u'\xe9l': return u'nek'
      elif featureset["bigram"] == u'\xe9n': return u'nek'
      elif featureset["bigram"] == u'\xe9p': return u'nek'
      elif featureset["bigram"] == u'\xe9r': return u'nek'
      elif featureset["bigram"] == u'\xe9s': return u'nek'
      elif featureset["bigram"] == u'\xe9t': return u'nek'
      elif featureset["bigram"] == u'\xe9v': return u'nek'
      elif featureset["bigram"] == u'\xe9z': return u'nek'
      elif featureset["bigram"] == u'\xedn': return u'nek'
      elif featureset["bigram"] == u'\xedr': return u'nek'
      elif featureset["bigram"] == u'\xedz': return u'nek'
      elif featureset["bigram"] == u'\xf3d': return u'nak'
      elif featureset["bigram"] == u'\xf3p': return u'nak'
      elif featureset["bigram"] == u'\xf6g': return u'nek'
      elif featureset["bigram"] == u'\xf6k': return u'nek'
      elif featureset["bigram"] == u'\xf6r': return u'nek'
      elif featureset["bigram"] == u'\xf6z': return u'nek'
      elif featureset["bigram"] == u'\xfar': return u'nak'
      elif featureset["bigram"] == u'\u0151d': return u'nek'
      elif featureset["bigram"] == u'\u0171n': return u'nek'
    return u'nek'

